"""initial friendships

Revision ID: d2ce850bcdbe
Revises: f6da96513c7c
Create Date: 2024-03-02 01:12:23.544093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ce850bcdbe'
down_revision: Union[str, None] = 'f6da96513c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('fk_friendships_target_id_users')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friendships_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships')),
        sa.UniqueConstraint('id', name=op.f('uq_friendships_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_friendships_target_id_users"), "friendships")
    op.drop_constraint(op.f("fk_friendships_user_id_users"), "friendships")
    op.drop_table('friendships')
    # ### end Alembic commands ###
