"""initial users

Revision ID: f6da96513c7c
Revises: 3465622b0488
Create Date: 2024-02-28 16:50:06.167354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6da96513c7c'
down_revision: Union[str, None] = '3465622b0488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", name=op.f("uq_users_id")),
        
        sa.Column("login", sa.String(30), nullable=False),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
        
        sa.Column("email", sa.String(50), nullable=False),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        
        sa.Column("phone", sa.String(20), nullable=True),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
        
        sa.Column("password", sa.String(64), nullable=False),
        sa.Column("countryCode", sa.String(2), nullable=False),
        sa.Column("isPublic", sa.Boolean(), nullable=False),
        sa.Column("image", sa.String(200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
